### ISSUE TITLE
Fizzbuzz & Refactoring

### ISSUE THREAD

**Issue by tjsgh531** [3lee1jeon/31_Fizzbuzz#3]
##Description

15의 배수일 경우 fizzbuzz를 프린트 하겠습니다.

##Tasks

- [x] 15의 배수일 경우 Fizzbuzz 프린트 하기
- [x] if를 하나만 사용하여 구현 

## Reference

[github 협업하기](https://www.youtube.com/watch?v=g3GEnjppUV0&feature=youtu.be)

**Comment by dltngud1541** [comment]
자네 감봉일세.
